name: Build Windows/macOS/Linux/Android
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Install Linux compile dependencies
        run: |
          sudo apt update
          sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev libwebkit2gtk-4.1-0 libwebkit2gtk-4.1-dev libsoup-3.0-0 libgbm-dev
      - name: Remove flutter_sound dependency
        run: |
          sed -i '/flutter_sound:/d' pubspec.yaml
          flutter pub get
      - run: flutter build linux --release
      - name: Package zip
        run: zip -r Linux-x64.zip build/linux/x64/release/bundle
      - uses: actions/upload-artifact@v4
        with:
          name: Linux-x64-Bundle
          path: Linux-x64.zip

  build-windows:
    runs-on: windows-latest
    env:
      CXXFLAGS: "-D_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS"
      CFLAGS: "-D_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS"
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build windows --release
      - name: Package zip
        run: Compress-Archive build/windows/x64/runner/Release Windows-x64.zip
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-x64-Bundle
          path: Windows-x64.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Remove flutter_sound dependency
        run: |
          sed -i '' '/flutter_sound:/d' pubspec.yaml
          flutter pub get
      - run: flutter build macos --release
      - name: Package zip
        run: zip -r macOS-App.zip build/macos/Build/Products/Release/*.app
      - uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: macOS-App.zip

  build-android-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Fix NDK + force lower androidx versions
        run: |
          sed -i '/android {/a ndkVersion = "28.2.13676358"' android/app/build.gradle.kts
          # 强制锁定低版本androidx，适配AGP 8.7.0
          sed -i '/dependencies {/a constraints { implementation("androidx.core:core-ktx:1.17.0") implementation("androidx.activity:activity-ktx:1.9.3") implementation("androidx.browser:browser:1.8.0") }' android/app/build.gradle.kts
          echo "android.disableAarMetadataCheck=true" >> android/gradle.properties
          flutter pub get
      - run: flutter build apk --release --android-skip-build-dependency-validation --no-tree-shake-icons
      - uses: actions/upload-artifact@v4
        with:
          name: Android-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk